- name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "*.bin"
          git lfs track "*.safetensors"
          git add .gitattributes

      - name: Clone from Hugging Face
        run: |
          git clone https://huggingface.co/Xenova/whisper-tiny hf_repo
          rm -rf hf_repo/.git
          cp -r hf_repo/* .
          rm -rf hf_repo

      - name: Push to GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
          
          # הוספה וביצוע commit עם תמיכת LFS
          git add .
          git commit -m "Sync from Hugging Face with LFS"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
